### ISSUE TITLE
PolylineStepWalker walks for only one seconds

### ISSUE THREAD

**Issue by th3w4y** [th3w4y/PokemonGo-Bot#28]
### Expected Behavior

should walk the full distance

### Actual Behaviour
* returns only next point to the navigator
* reinitialises itself on next step consuming from the Google Walking directions quota
### Other Information
OS: 
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)

**Comment by th3w4y** [comment]
added a while loop in the step method to fix this

```
    def step(self):
        cLat, cLng = self.api._position_lat, self.api._position_lng
        while (cLat, cLng) != self.polyline_walker.get_pos()[0]
            self.polyline_walker.unpause()
            sleep(1)
            self.polyline_walker.pause()
            cLat, cLng = self.polyline_walker.get_pos()[0]
            self.api.set_position(round(cLat, 5), round(cLng, 5), 0)
            self.bot.heartbeat()
        return True
```

**Comment by douglascamata** [comment]
@th3w4y remember that it needs to walk just a little bit, than return the control to the bot for the next tick.

**Comment by th3w4y** [comment]
Problem with that approach would be:
- a new StepWalker would be instantiated... (thus you will do one Google API call every second..)
- why is a new step walker instantiated every time?


>@th3w4y remember that it needs to walk just a little bit, then return the control to the bot for the >next tick to process workers. So adding a loop is wrong, because it will do a blink walk without >interacting with anything.

**Comment by th3w4y** [comment]
```
    def take_step(self):
        point = self.points[self.ptr]
        self.cnt += 1

        if self.config.walk > 0:
            step_walker = StepWalker(
                self.bot,
                self.config.walk,
                point['lat'],
                point['lng']
            )

            dist = distance(
                self.api._position_lat,
                self.api._position_lng,
                point['lat'],
                point['lng']
            )
    def take_step(self):
        point = self.points[self.ptr]
        self.cnt += 1

        if self.config.walk > 0:
            step_walker = StepWalker(
                self.bot,
                self.config.walk,
                point['lat'],
                point['lng']
            )

            dist = distance(
                self.api._position_lat,
                self.api._position_lng,
                point['lat'],
                point['lng']
            )
```

**Comment by th3w4y** [comment]
I thing the navigator should have a self.stepper =StepWalker()
and update the self.stepper only if it no longer want to go towards same pokestop...
